spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    s3:
      bucket: "workmeong"
    credentials:
      accessKey: ${S3_ACCESS}
      secretKey: ${S3_SECRET}
    stack.auto: false
    region:
      static: ap-northeast-2
