apiVersion: "v1"
data:
  S3_ACCESS: "QUtJQTNGTEQ0RkpEWUJWMktCNEcK"
  S3_SECRET: "M1A3QzJTTWZ1ejNFU05vaHJaOFhuVEJhbExEUVF6WmM4NGtwRXFITwo="
kind: "Secret"
metadata:
  name: "backend-env"
type: "Opaque"
    
